### ISSUE TITLE
使用VideoActivity.open...会将原来开启的activity 关闭

### ISSUE THREAD

**Issue by JuneLeGency** [ymback/BambooPlayer#1]
暂时查不到原因，仔细看了好几遍代码还是不知道在哪里被kill的，好像是在so里面 不知道你有发现这个问题么

**Comment by JuneLeGency** [comment]
兄弟Video里面没事不要killPID啊 掌握好 release方法 kill的话 整个其他Activity都挂了

**Comment by ymback** [comment]
自己改下发PR吧，我最近没时间做这个东西。。。

**Comment by JuneLeGency** [comment]
恩 不过我还是发现了问题 但是不知道怎么回事 我试了下原来的那个demo库没有这个问题 他的夜视kill pid

我给你详细描述下 你有空看一下
Vitamio Demo中
启动A activity ——》启动VideoActivity
退出Video 会保留原来的A activity  显示  A 和 VideoActivity 两个的PID不同

Bamboo 

用同样方式 会把两个Activity 都杀死   两个Activity的pid相同

我对Activity 进程不是很熟 你有空帮忙分析下

**Comment by JuneLeGency** [comment]
找到原因了 在https://github.com/ymback/BambooPlayer/blob/master/BambooPlayer/AndroidManifest.xml#L299

请加上 process

让activity 以进程方式启动。

**Comment by JuneLeGency** [comment]
记得对应的service也要加上 process 两个名字相同

如果两个都不加process 默认 进程的activity 都在一个进程 在退出的时候 会把同一进程下activity 杀死导致 启动的activity 不能保持。
